name: Script Testing

on:
  push:
    branches:
      - main
  # Enable manual running of workflow, so we can force execution
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.3"
      - uses: catchpoint/workflow-telemetry-action@v2
      - run: |
          python -m pip install simpleitk==2.4.0
          python script.py
